## You should change each of the following fields
## to customize your blog

title: Data Science (for us simple minded folks)
description: > 
  "If you're a newbie and are trying to learn more about the Data Science world... WELCOME!! This blog will be perfect for you! Nothing against the professionals and geniuses out there! You're more than welcomed to stay! Listen, I know how difficult it can be starting out in the data science world so this is a blog for others (who are not as experienced) to feel welcomed and at ease. This is the type of blog that I wished I would've read when I was starting my career out. I hope it helps you!" 
author: Liz Mendoza
author_description: | 
  "Hey there! I'm Liz! I'm a senior at Brigham Young University studying Statistics with a Data Science emphasis. I'm also double minoring in Business and Information Systems. I know what you're probably thinking. Probably the same as every other person I've met. "Whoa! You must be super smart!" or "That's intense!" The truth is, I don't really consider myself the smartest nor the brightest but I'm a great story teller! So let me paint a picture for you of my journey...I started my college career as pre-med. I was planning on being a doctor from the age of 12-21. All throughout high school, I shadowed doctors and nurses.  I took several health classes during that time and started taking more during college. Then I realized I couldn't see myself being a doctor my whole life. Started taking a coding class out of nowhere and started taking more statistics classes and here I am now. High school me would die if she found out I was doing this today. As someone who had NO IDEA what data science or coding or statistics was before my sophomore year of college, I understand if you're new and feel lost. It's normal! I understand the "imposter syndrome" and I understand, well, not understanding fancy data science textbooks. So yeah, I'm Liz. Just a Mexican-American girl trying to make it into the Data Science world and trying to help others along the way too!" 

url: https://LiztheWz.github.io ## change this to https://yourusername.github.io
baseurl: /My386Blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: LiztheWz
    twitter: 
    facebook: 
    email: lizethm3@byu.edu
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




