## You should change each of the following fields
## to customize your blog

title: My Stat 386 Blog
description: "This will have a more detailed description about my Stat 386 blog." 
author: Liz Mendoza
author_description: "Senior at Brigham Young University studying Statistics with a Data Science emphasis.
Double minoring in Business and Information Systems." 

url: https://LiztheWz.github.io ## change this to https://yourusername.github.io
baseurl: /My386Blog ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: LiztheWz
    twitter: 
    facebook: 
    email: lizethm3@byu.edu
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




